// Character roster for lobby picker. Each entry points to a 60×448 sprite sheet
// (1 col × 4 rows: DL, UL, UR, DR top→bottom) generated by scripts/tile-sprites.mjs.
//
// To add a new character:
//   1. node scripts/tile-sprites.mjs --in assets/<name>_raw.jpg --out public/assets/<name>.png
//   2. Append a new entry below.

export interface Character {
  id: string
  name: string
  sprite: string           // path served from /public
}

export const CHARACTERS: Character[] = [
  { id: 'monkey',   name: 'Monkey',   sprite: '/assets/owner.png' },
  { id: 'pug',      name: 'Pug',      sprite: '/assets/pug.png' },
  { id: 'keeshond', name: 'Keeshond', sprite: '/assets/keeshond.png' },
  { id: 'capybara', name: 'Capybara', sprite: '/assets/capybara.png' },
  { id: 'elephant', name: 'Elephant', sprite: '/assets/elephant.png' },
]

export const DEFAULT_P1_CHAR = 'monkey'
export const DEFAULT_P2_CHAR = 'pug'

export function getCharacter(id: string): Character {
  return CHARACTERS.find(c => c.id === id) || CHARACTERS[0]
}
